### ISSUE TITLE
Updating recurring donation amounts?

### ISSUE THREAD

**Issue by JoeMurray** [adixon/ca.civicrm.moneris#1]
Alan, I'm wondering if you would be interested in publishing this extension? If so, we'd like to contribute some code that allows recurring donation amounts to be updated or deleted.

**Comment by adixon** [comment]
Oh excellent, I've been meaning to write to you, remembering that you'd done some work on this at some point. All I've got here is the core code + the php 'api' file that we couldn't include in CiviCRM for licensing reasons.

Send me your code in whatever format you like ...

And yes, my goal was to publish it at civicrm and get them to remove most of the core code which is really not useful. Unlike the iATS extension, this one actually replaces the core code.

**Comment by JoeMurray** [comment]
We'll try to get to this in January then. Not sure about what you mean about getting them to remove code - do you mean the Moneris stuff in core?

**Comment by adixon** [comment]
Remove code - yes, the moneris core code. Not a priority.

I've got a client who'd be interested in this maybe sooner - can you just throw me a copy of your code as is?

**Comment by laryn** [comment]
Is this extension stable/usable? Does it work in the US or only Canada? 

I have never used Moneris but had someone ask if CiviCRM supported it and am doing some research to respond to them.

**Comment by adixon** [comment]
I'm probably the only one using it, on a couple of newish sites, both using 4.5.

The recurring stuff is fragile, and it's built to support US but doesn't yet.

It's solid enough for one-time credit card payments.
