### ISSUE TITLE
Status of the Moneris Extension

### ISSUE THREAD

**Issue by awasson** [adixon/ca.civicrm.moneris#10]
I've been scouring the CiviCRM Extension Directory (https://civicrm.org/extensions) for the Moneris extension and I don't see it there but found a link from StackExchange to this Repo. 

I prefer to use extensions that are integrated from the CiviCRM Extension Directory because CiviCRM lets me know when it's time to do updates. Is there any reason this extension isn't included in the official directory?

Thanks,
Andrew

**Comment by adixon** [comment]
Weakness of character?
