### ISSUE TITLE
Malformed XML bug with recurring contributions?

### ISSUE THREAD

**Issue by Edzelopez** [adixon/ca.civicrm.moneris#6]
Hi @adixon !

We keep getting this error when we do a recurring donation using Moneris. The response is:

`mpgResponse Object
(
    [responseData] => Array
        (
            [ReceiptId] => dbd0ebb676bc03ce47c9d1dcf3b526e6
            [ReferenceNum] => null
            [ResponseCode] => null
            [ISO] => null
            [AuthCode] => null
            [TransTime] => null
            [TransDate] => null
            [TransType] => null
            [Complete] => true
            [Message] => ** ERROR ** - unable to register recurring transaction!
            [TransAmount] => null
            [CardType] => null
            [TransID] => null
            [TimedOut] => false
            [Ticket] => null
            [RecurSuccess] => false
            [IsVisaDebit] => false
        )
    [p] => Resource id #406
    [currentTag] => /dev/null
    [purchaseHash] => Array
        (
        )

    [refundHash] => 
    [correctionHash] => Array
        (
        )

    [isBatchTotals] => 0
    [term_id] => 
    [receiptHash] => Array
        (
        )

    [ecrHash] => Array
        (
        )

    [CardType] => 
    [currentTxnType] => 
    [ecrs] => Array
        (
        )

    [cards] => Array
        (
        )

    [cardHash] => Array
        (
        )

    [ACSUrl] => 
)`
Response code = null suggests this is a malformed XML error; Debugging the XML we get,

`<?xml version="1.0"?><request><store_id>store5</store_id><api_token>yesguy</api_token><card_verification><order_id>ada74198cea8f75936a49133391faee2</order_id><cust_id></cust_id><pan>4111111111111111</pan><expdate>2508</expdate><crypt_type>7</crypt_type><cust_info><email>joe.murray@jmaconsulting.biz</email><instructions></instructions><billing><first_name>Joseph</first_name><last_name>Murray</last_name><company_name></company_name><address>57 Grandview Ave</address><city>Toronto</city><province>ON</province><postal_code>M4K 1J1</postal_code><country>CA</country><phone_number></phone_number><fax></fax><tax1></tax1><tax2></tax2><tax3></tax3><shipping_cost></shipping_cost></billing></cust_info></card_verification></request><?xml version="1.0"?><request><store_id>store5</store_id><api_token>yesguy</api_token><purchase><order_id>ada74198cea8f75936a49133391faee2</order_id><cust_id></cust_id><amount></amount><pan>4111111111111111</pan><expdate>2508</expdate><crypt_type>7</crypt_type><dynamic_descriptor></dynamic_descriptor><recur><recur_unit>month</recur_unit><start_now>false</start_now><start_date>2019/04/20</start_date><num_recurs>99</num_recurs><period>1</period><recur_amount>15.00</recur_amount></recur></purchase></request>`

Seems as though <?xml version="1.0"?> is indicated twice in the XML sent to Moneris. Not sure if this is intentional, but parsers indicate this as an error. Any thoughts here?

**Comment by Edzelopez** [comment]
Edit: It might be the case that the debug is returning both xmls one after the other as the function is called multiple times. In which case, please ignore my assumption of <?xml version="1.0"?> being written twice.

**Comment by adixon** [comment]
I haven't changed this code for a long time, so I think you're misdiagnosing the error.

I do have two clients actively using this extension, but neither of them use recurring contributions, which isn't generally recommended with this extension. Are you sure you're using this copy of the moneris extension? Are your sure the moneris account has recurring enabled?

My best guess is that the protocol for generating recurring contributions that this extension uses has (finally) been removed, this code was written about 12 years ago ...
